server:
  port: 9580
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:~/appdb;AUTO_SERVER=TRUE'
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  liquibase:
    change-log: 'classpath:changelog.yaml'
